// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUIGVCVAu2U6GPw4y-hXlHhOpKRnmaE-o',
    appId: '1:143685480306:web:7a605f0e541b1bdc0077eb',
    messagingSenderId: '143685480306',
    projectId: 'shoutout-83240',
    authDomain: 'shoutout-83240.firebaseapp.com',
    storageBucket: 'shoutout-83240.firebasestorage.app',
    measurementId: 'G-21BZT3HLRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyzXyGjy4pVArAlmf0L-hnj4H8H-MkNMk',
    appId: '1:143685480306:android:f76a22af491a8a0b0077eb',
    messagingSenderId: '143685480306',
    projectId: 'shoutout-83240',
    storageBucket: 'shoutout-83240.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaUxxGixxa_w0WvJAAQqsgJzfHi6fzD6E',
    appId: '1:143685480306:ios:ddcabb0ab3ca7ab90077eb',
    messagingSenderId: '143685480306',
    projectId: 'shoutout-83240',
    storageBucket: 'shoutout-83240.firebasestorage.app',
    iosClientId: '143685480306-4bmk4173d258hplva6jm9dvju7ob30cq.apps.googleusercontent.com',
    iosBundleId: 'com.mckintoye.shoutoutapp',
  );
}
